require 'uri'
require_relative 'paymentwall/deprecated/base.rb'
require_relative 'paymentwall/base.rb'
require_relative 'paymentwall/pingback.rb'
require_relative 'paymentwall/product.rb'
require_relative 'paymentwall/widget.rb'
